- hosts: dev
  become: yes
  vars:
    app_dest: /opt/app
    repo_url: "{{ repo_url | default('https://github.com/Nicolas-Tondeur/exercice-global.git') }}"
    branch: "dev"
  roles:
    - role: ../roles/app