- hosts: prod
  become: yes
  vars:
    app_dest: /opt/app
    repo_url: "{{ repo_url | default('https://github.com/Nicolas-Tondeur/exercice-global.git') }}"
    branch: "main"
  roles:
    - role: ../roles/app