- name: Déploiement PROD
  hosts: prod
  become: yes  # exécuter les tâches en root
  tasks:

    - name: Installer les dépendances
      apt:
        name:
          - git
          - nginx
        state: present
        update_cache: yes

    - name: Cloner le dépôt depuis GitHub
      git:
        repo: 'https://github.com/Nicolas-Tondeur/exercice-global.git'
        dest: /opt/app
        force: yes

    - name: Copier les fichiers de l'application vers Nginx
      copy:
        src: /opt/app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted

    - name: Créer fichier de log de confirmation
      copy:
        content: "Déploiement DEV terminé le {{ ansible_date_time.date }} à {{ ansible_date_time.time }}"
        dest: /opt/app/deploy.log