name: CI/CD Pipeline

on:
  push:
    branches: [ dev, main ]

jobs:
  ci:
    name: Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install
        working-directory: app

      - name: Run tests
        run: npm test
        working-directory: app


  deploy:
    name: Deploy (ansible)
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Python & Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ github.ref == 'refs/heads/dev' && secrets.ID_RSA_DEV || secrets.ID_RSA_PROD }}

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          ansible-playbook -i ansible/inventory/dev.ini ansible/playbooks/deploy-dev.yml

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        run: |
          ansible-playbook -i ansible/inventory/prod.ini ansible/playbooks/deploy-prod.yml

      - name: known_hosts ajout
        run: |
          ssh-keyscan -p 2222 -H 54.198.132.209 >> ~/.ssh/known_hosts || true
          ssh-keyscan -p 2200 -H 54.198.132.209 >> ~/.ssh/known_hosts || true